### ISSUE TITLE
Align on brackets

### ISSUE THREAD

**Issue by Tolmark12** [adrianlee44/atom-aligner#25]
I write my scss like so:

```scss
.parent      { color:red; width:100px;
  .child-a   { color:blue; width:50px; }
  .child-b   { color:green;
    .sub     { color:purple; }
  }
}
```

Would it be possible to write an aligner extension that accomplishes this? I've tried forking the scss package and aligning on the ```{```, which works well for items that are indented to the same column, but doesn't work for lines that have different indentation.
