### ISSUE TITLE
aligner for salt states

### ISSUE THREAD

**Issue by dgmorrisjr** [adrianlee44/atom-aligner#71]
Hi @adrianlee44  - I've been using your atom-aligner for python and it works great.   But I find myself wanting to also use this same functionality in the Salt States that i develop.  (SaltStack files ending in .sls extension).   These are essentially files that contain python, jinja, and yaml content.

I was looking through the source for the atom-aligner-python.   I'm wondering if it's just a matter of copying this project and then changing the `selector` list in the `provider.js` file?

I've never developed anything for atom... so not even sure how to determine what the selector options for a salt (sls) file would be.   I started reading the Atom development documentation... haven't found it quite yet... but wanted to see what your thoughts on this are.

**Comment by dgmorrisjr** [comment]
I found this in the language-salt package settings `source.salt`

**Comment by adrianlee44** [comment]
Hi @dgmorrisjr,
You can copy the same format in the python and port it over for Salt States. The selector would change to `.source.salt`.

What are you trying to align? In order for aligner to work, you would need to figure out the scope of the character you are trying to align. You can do `cmd-alt-p` or search for "Log cursor scope" in the command palette.

**Comment by dgmorrisjr** [comment]
Thanks for the help, 

Here is an example of content of a salt state... this file could be `<filename>.sls`:
```
{% set service_name = 'sftp' %}
{% set domain = pillar['var']['domain'] %}
{% set encryption_key = pillar['myapp']['encryption_key'] %}

# should be a grain
{% set interface_api_key = salt['grains.get']('interface_api_keys')['sftp'] %}

include:
  - software.interface.configure

install_iface_sftp_app_config_file:
  file.managed:
    - name: /opt/myapp/sftp-daemon.properties
    - source: salt://myapp/conf/sftp-daemon-.properties.jinja
    - user: root
    - group: myapp
    - mode: 660
    - makedirs: True
    - template: jinja
    - defaults:
        domain: {{ domain }}
        service_name: {{ service_name }}
        encryption_key: {{ encryption_key }}
        api_key: {{ interface_api_key }}
```

When the cursor is over the Jinja Set Statements, the scope that's revealed when pressing `alt+cmd+p` is `source.salt`, `meta.scope.jinja.tag`, and `variable.other.jinja`.

When the cursor is over any of the Yaml Key Names, the scope that's revealed is: `source.salt`, and `entity.name.tag.yaml`.  Then when the cursor is over the Yaml Values, the scope that's revealed is:  `source.salt`, `string.unquoted.yaml`.

If my cursor is in the Jinja set statements or i've highlighted a block of jinja statements, and then press the `ctrl+cmd+/` to invoke the aligner, the jinja is properly aligned into this:
```
{% set service_name   = 'sftp' %}
{% set domain              = pillar['var']['domain'] %}
{% set encryption_key = pillar['myapp']['encryption_key'] %}
```

So that works as i would expect it to.

However, when I have the cursor positioned in the yaml statements, and press `ctrl+cmd+/` to invoke aligner, nothing happens.   

I currently have the selector statement as:
```
  selector: [
    '.source.python',
    '.source.embedded.python',
    '.source.salt',
  ],
```

But i've tried individually adding the following lines to the `selector` statement:
`'.yaml',`
`'entity.name.tag.yaml',`
`'string.unquoted.yaml',`

between each time, i would shutdown atom and restart it to ensure it was reloading the modules correctly.
